"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
includefiles = [('functions/', 'functions/'),
                ('images/', 'images/'),
                ('qml/', 'qml/'),
                ('logo_icon.svg', 'logo_icon.svg')
                ]

APP = ['main.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=includefiles,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

