"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import glob

from setuptools import setup

APP = ['main.py']
DATA_FILES = [('functions', glob.glob('functions/*.*')),
              ('images/svg_images', glob.glob('images/svg_images/*.*')),
              ('qml', glob.glob('qml/*.*')),
              ('qml/controls', glob.glob('qml/controls/*.*')),
              ('qml/pages', glob.glob('qml/pages/*.*'))]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
