# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lock_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LockScreen(object):
    def setupUi(self, LockScreen):
        LockScreen.setObjectName("LockScreen")
        LockScreen.resize(800, 600)
        LockScreen.setStyleSheet("background-color: rgb(35, 33, 30);")
        self.centralwidget = QtWidgets.QWidget(LockScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        LockScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LockScreen)
        QtCore.QMetaObject.connectSlotsByName(LockScreen)

    def retranslateUi(self, LockScreen):
        _translate = QtCore.QCoreApplication.translate
        LockScreen.setWindowTitle(_translate("LockScreen", "MainWindow"))
        self.label.setText(_translate("LockScreen", "LOCKED"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LockScreen = QtWidgets.QMainWindow()
    ui = Ui_LockScreen()
    ui.setupUi(LockScreen)
    LockScreen.show()
    sys.exit(app.exec_())
