# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dashboard_btn = QtWidgets.QPushButton(self.frame_left_menu)
        self.dashboard_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.dashboard_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.dashboard_btn.setObjectName("dashboard_btn")
        self.verticalLayout_3.addWidget(self.dashboard_btn)
        self.view_btn = QtWidgets.QPushButton(self.frame_left_menu)
        self.view_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.view_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.view_btn.setObjectName("view_btn")
        self.verticalLayout_3.addWidget(self.view_btn)
        self.add_btn = QtWidgets.QPushButton(self.frame_left_menu)
        self.add_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.add_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout_3.addWidget(self.add_btn)
        self.remove_btn = QtWidgets.QPushButton(self.frame_left_menu)
        self.remove_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.remove_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout_3.addWidget(self.remove_btn)
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.frame_top_menus)
        self.setting_btn = QtWidgets.QPushButton(self.frame_left_menu)
        self.setting_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.setting_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.setting_btn.setObjectName("setting_btn")
        self.verticalLayout_3.addWidget(self.setting_btn)
        self.horizontalLayout.addWidget(self.frame_left_menu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(715, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard_page = QtWidgets.QWidget()
        self.dashboard_page.setObjectName("dashboard_page")
        self.gridLayout = QtWidgets.QGridLayout(self.dashboard_page)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.dashboard_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lockscreen_btn = QtWidgets.QPushButton(self.dashboard_page)
        self.lockscreen_btn.setObjectName("lockscreen_btn")
        self.gridLayout.addWidget(self.lockscreen_btn, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.dashboard_page)
        self.view_page = QtWidgets.QWidget()
        self.view_page.setObjectName("view_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.view_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.view_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.view_page)
        self.add_page = QtWidgets.QWidget()
        self.add_page.setObjectName("add_page")
        self.page_name = QtWidgets.QLabel(self.add_page)
        self.page_name.setGeometry(QtCore.QRect(280, 10, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_name.sizePolicy().hasHeightForWidth())
        self.page_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.page_name.setFont(font)
        self.page_name.setAutoFillBackground(False)
        self.page_name.setStyleSheet("color: #ffffff;")
        self.page_name.setAlignment(QtCore.Qt.AlignCenter)
        self.page_name.setObjectName("page_name")
        self.image = QtWidgets.QLabel(self.add_page)
        self.image.setGeometry(QtCore.QRect(220, 110, 231, 221))
        self.image.setMinimumSize(QtCore.QSize(231, 221))
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image.setLineWidth(2)
        self.image.setMidLineWidth(2)
        self.image.setText("")
        self.image.setObjectName("image")
        self.splitter = QtWidgets.QSplitter(self.add_page)
        self.splitter.setGeometry(QtCore.QRect(100, 450, 491, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.turn_on = QtWidgets.QPushButton(self.splitter)
        self.turn_on.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.turn_on.setFont(font)
        self.turn_on.setStyleSheet("color: #ffffff;")
        self.turn_on.setObjectName("turn_on")
        self.capture = QtWidgets.QPushButton(self.splitter)
        self.capture.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.capture.setFont(font)
        self.capture.setStyleSheet("color: #ffffff;")
        self.capture.setObjectName("capture")
        self.turn_off = QtWidgets.QPushButton(self.splitter)
        self.turn_off.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.turn_off.setFont(font)
        self.turn_off.setStyleSheet("color: #ffffff;")
        self.turn_off.setObjectName("turn_off")
        self.stackedWidget.addWidget(self.add_page)
        self.remove_page = QtWidgets.QWidget()
        self.remove_page.setObjectName("remove_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.remove_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.remove_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.remove_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.setting_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.setting_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.setting_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dashboard_btn.setText(_translate("MainWindow", "Dashboard"))
        self.view_btn.setText(_translate("MainWindow", "View"))
        self.add_btn.setText(_translate("MainWindow", "Add"))
        self.remove_btn.setText(_translate("MainWindow", "Remove"))
        self.setting_btn.setText(_translate("MainWindow", "Setting"))
        self.label.setText(_translate("MainWindow", "Dashboard"))
        self.lockscreen_btn.setText(_translate("MainWindow", "LOCK SCREEN"))
        self.label_2.setText(_translate("MainWindow", "View Faces"))
        self.page_name.setText(_translate("MainWindow", "Add Faces"))
        self.turn_on.setText(_translate("MainWindow", "Turn On Camera"))
        self.capture.setText(_translate("MainWindow", "Capture"))
        self.turn_off.setText(_translate("MainWindow", "Turn Off Camera"))
        self.label_4.setText(_translate("MainWindow", "Remove Faces"))
        self.label_5.setText(_translate("MainWindow", "Setting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
